// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIjp64m_1n5VnHWNR7Wh80NHBFSxervrc',
    appId: '1:859087089071:web:884b3326d440931a02d35a',
    messagingSenderId: '859087089071',
    projectId: 'celam-f4fd6',
    authDomain: 'celam-f4fd6.firebaseapp.com',
    storageBucket: 'celam-f4fd6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkA8JNBpgXfK4nKEt6h-TaqrAZ0Tm0bdw',
    appId: '1:859087089071:android:1264d80fe4aee53002d35a',
    messagingSenderId: '859087089071',
    projectId: 'celam-f4fd6',
    storageBucket: 'celam-f4fd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIqnV0NRIjTAVlExMsDzu5Y7GvLI2PMzo',
    appId: '1:859087089071:ios:862f1a6a700f76d802d35a',
    messagingSenderId: '859087089071',
    projectId: 'celam-f4fd6',
    storageBucket: 'celam-f4fd6.appspot.com',
    iosBundleId: 'com.example.celam',
  );
}
